export const Theme = {
    fontFamily: 'Montserrat',
    palette: {
    primary1Color: '#1B2028',
        primary2Color: '#28323B',
        primary3Color: '#313D50',
        accent1Color: '#CC8F1B',
        accent2Color: '#EFAD00',
        accent3Color: '#E9A916',
        textColor: '#ffffff',
        alternateTextColor: '#ffffff',
        canvasColor: '#1B2028',
        borderColor: '#ffffff',
        disabledColor: '#C3C3C3',
        pickerHeaderColor: '#1B2028',
        clockCircleColor: '#1B2028',
        shadowColor: '#1B2028',
    },
    slider: {
        trackColor: '#ffffff',
            trackColorSelected: '#ffffff',
            handleColorZero: '#ffffff',
            handleFillColor: '#CC8F1B',
            selectionColor: '#EFAD00',
            rippleColor: '#313D50',
            handleSizeActive: 22,
            handleSizeDisabled: 12,
            handleSize: 16,
    },
    stepper: {
        backgroundColor: 'transparent',
        hoverBackgroundColor: '#313D50',
        iconColor: '#CC8F1B',
        hoveredIconColor: '#CC8F1B',
        inactiveIconColor: '#ffffff',
        textColor: '#ffffff',
        disabledTextColor: '#b3b3b3',
        connectorLineColor: '#ffffff',
    },
    snackbar: {
        textColor:  '#ffffff',
        backgroundColor: 'transparent',
    },
}