export const paymentConstants = {
    API_PATH: 'http://localhost:3737/payment',

    PAYMENT_REQUEST: 'USERS_PAYMENT_REQUEST',
    PAYMENT_SUCCESS: 'USERS_PAYMENT_SUCCESS',
    PAYMENT_FAILURE: 'USERS_PAYMENT_FAILURE',

    STEPPER_FINISHED: 'PAYMENT_STEPPER_FINISHED',
    STEPPER_CHANGED: 'PAYMENT_STEPPER_CHANGED',

    AMOUNT_CHANGED: 'PAYMENT_AMOUNT_CHANGED'
};