export const pushConstants = {
    PUSH_SUBSCRIPTION_REQUEST: 'PUSH_NOTIFICATION_SUBSCRIPTION_REQUEST',
    PUSH_SUBSCRIPTION_SUCCESS: 'PUSH_NOTIFICATION_SUBSCRIPTION_SUCCESS',
    PUSH_SUBSCRIPTION_FAILURE: 'PUSH_NOTIFICATION_SUBSCRIPTION_FAILURE',

    PUSH_UNSUBSCRIPTION_REQUEST: 'PUSH_NOTIFICATION_UNSUBSCRIPTION_REQUEST',
    PUSH_UNSUBSCRIPTION_SUCCESS: 'PUSH_NOTIFICATION_UNSUBSCRIPTION_SUCCESS',
    PUSH_UNSUBSCRIPTION_FAILURE: 'PUSH_NOTIFICATION_UNSUBSCRIPTION_FAILURE',

    PUSH_PERMISSION_REQUEST: 'PUSH_PERMISSION_REQUEST',
    PUSH_PERMISSION_SUCCESS: 'PUSH_PERMISSION_SUCCESS',
    PUSH_PERMISSION_FAILURE: 'PUSH_PERMISSION_FAILURE',
};