export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    USER_UPDATE: 'UPDATE_LOCAL_USER',

    RANK_UPDATE: 'UPDATE_USER_RANK',

    PRESTIGE_UPDATE: 'UPDATE_PRESIGE_USER',

    PUSH_TOKEN_UNSUBSCRIBE: 'PUSH_TOKEN_UNSUBSCRIBE',
    PUSH_TOKEN_SUBSCRIBE: 'PUSH_TOKEN_SUBSCRIBE',

    LOGOUT: 'USERS_LOGOUT',
    LOGOUT_USER: 'USERS_DELETE_LOCAL',

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE',

    RE_AUTH_REQUEST: 'USERS_RE_AUTH_REQUEST',
    RE_AUTH_SUCCESS: 'USERS_RE_AUTH_SUCCESS',
    RE_AUTH_FAILURE: 'USERS_RE_AUTH_FAILURE',

    USER_EMAIL_EXIST_SUCCESS: 'USER_EMAIL_DOES_EXIST',
    USER_EMAIL_EXIST_FAILURE: 'USER_EMAIL_DOES_NOT_EXIST',
};